apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      containers:
      - image: flask-app-py27env
        name: python27_baseenv
        env:
        - name: FLASK-APP-DB-HOST
          value: flask-app-db
        - name: FLASK-APP-DB-PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 5000
          name: flask-app
        volumeMounts:
        - name: flask-app-persistent-storage
          mountPath: /usr/local/code
      volumes:
      - name: flask-app-persistent-storage
        persistentVolumeClaim:
          claimName: flask-app-data-pv-claim